export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CONFERENCE_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const CONFERENCEITEM_ROUTE = '/conference'
export const LC_ROUTE = '/lc'
export const CONFREG_ROUT = '/confreg'
export const CONFIRMITION_ROUTE = '/confirmition'

export const CONFERENCEITEMADMIN_ROUTE = '/conferenceadmin'